export const PROVINCES_SEED = [
  // Bắc (25)
  { name: 'Hà Nội', slug: 'ha-noi', region: 'bac', code: 1 },
  { name: 'Hà Giang', slug: 'ha-giang', region: 'bac', code: 2 },
  { name: 'Cao Bằng', slug: 'cao-bang', region: 'bac', code: 4 },
  { name: 'Bắc Kạn', slug: 'bac-kan', region: 'bac', code: 6 },
  { name: 'Tuyên Quang', slug: 'tuyen-quang', region: 'bac', code: 8 },
  { name: 'Lào Cai', slug: 'lao-cai', region: 'bac', code: 10 },
  { name: 'Điện Biên', slug: 'dien-bien', region: 'bac', code: 11 },
  { name: 'Lai Châu', slug: 'lai-chau', region: 'bac', code: 12 },
  { name: 'Sơn La', slug: 'son-la', region: 'bac', code: 14 },
  { name: 'Yên Bái', slug: 'yen-bai', region: 'bac', code: 15 },
  { name: 'Hoà Bình', slug: 'hoa-binh', region: 'bac', code: 17 },
  { name: 'Thái Nguyên', slug: 'thai-nguyen', region: 'bac', code: 19 },
  { name: 'Lạng Sơn', slug: 'lang-son', region: 'bac', code: 20 },
  { name: 'Quảng Ninh', slug: 'quang-ninh', region: 'bac', code: 22 },
  { name: 'Bắc Giang', slug: 'bac-giang', region: 'bac', code: 24 },
  { name: 'Phú Thọ', slug: 'phu-tho', region: 'bac', code: 25 },
  { name: 'Vĩnh Phúc', slug: 'vinh-phuc', region: 'bac', code: 26 },
  { name: 'Bắc Ninh', slug: 'bac-ninh', region: 'bac', code: 27 },
  { name: 'Hải Dương', slug: 'hai-duong', region: 'bac', code: 30 },
  { name: 'Hải Phòng', slug: 'hai-phong', region: 'bac', code: 31 },
  { name: 'Hưng Yên', slug: 'hung-yen', region: 'bac', code: 33 },
  { name: 'Thái Bình', slug: 'thai-binh', region: 'bac', code: 34 },
  { name: 'Hà Nam', slug: 'ha-nam', region: 'bac', code: 35 },
  { name: 'Nam Định', slug: 'nam-dinh', region: 'bac', code: 36 },
  { name: 'Ninh Bình', slug: 'ninh-binh', region: 'bac', code: 37 },
  // Trung (19)
  { name: 'Thanh Hoá', slug: 'thanh-hoa', region: 'trung', code: 38 },
  { name: 'Nghệ An', slug: 'nghe-an', region: 'trung', code: 40 },
  { name: 'Hà Tĩnh', slug: 'ha-tinh', region: 'trung', code: 42 },
  { name: 'Quảng Bình', slug: 'quang-binh', region: 'trung', code: 44 },
  { name: 'Quảng Trị', slug: 'quang-tri', region: 'trung', code: 45 },
  { name: 'Thừa Thiên Huế', slug: 'thua-thien-hue', region: 'trung', code: 46 },
  { name: 'Đà Nẵng', slug: 'da-nang', region: 'trung', code: 48 },
  { name: 'Quảng Nam', slug: 'quang-nam', region: 'trung', code: 49 },
  { name: 'Quảng Ngãi', slug: 'quang-ngai', region: 'trung', code: 51 },
  { name: 'Bình Định', slug: 'binh-dinh', region: 'trung', code: 52 },
  { name: 'Phú Yên', slug: 'phu-yen', region: 'trung', code: 54 },
  { name: 'Khánh Hoà', slug: 'khanh-hoa', region: 'trung', code: 56 },
  { name: 'Ninh Thuận', slug: 'ninh-thuan', region: 'trung', code: 58 },
  { name: 'Bình Thuận', slug: 'binh-thuan', region: 'trung', code: 60 },
  { name: 'Kon Tum', slug: 'kon-tum', region: 'trung', code: 62 },
  { name: 'Gia Lai', slug: 'gia-lai', region: 'trung', code: 64 },
  { name: 'Đắk Lắk', slug: 'dak-lak', region: 'trung', code: 66 },
  { name: 'Đắk Nông', slug: 'dak-nong', region: 'trung', code: 67 },
  { name: 'Lâm Đồng', slug: 'lam-dong', region: 'trung', code: 68 },
  // Nam (19)
  { name: 'Bình Phước', slug: 'binh-phuoc', region: 'nam', code: 70 },
  { name: 'Tây Ninh', slug: 'tay-ninh', region: 'nam', code: 72 },
  { name: 'Bình Dương', slug: 'binh-duong', region: 'nam', code: 74 },
  { name: 'Đồng Nai', slug: 'dong-nai', region: 'nam', code: 75 },
  { name: 'Bà Rịa - Vũng Tàu', slug: 'ba-ria-vung-tau', region: 'nam', code: 77 },
  { name: 'TP. Hồ Chí Minh', slug: 'tp-hcm', region: 'nam', code: 79 },
  { name: 'Long An', slug: 'long-an', region: 'nam', code: 80 },
  { name: 'Tiền Giang', slug: 'tien-giang', region: 'nam', code: 82 },
  { name: 'Bến Tre', slug: 'ben-tre', region: 'nam', code: 83 },
  { name: 'Trà Vinh', slug: 'tra-vinh', region: 'nam', code: 84 },
  { name: 'Vĩnh Long', slug: 'vinh-long', region: 'nam', code: 86 },
  { name: 'Đồng Tháp', slug: 'dong-thap', region: 'nam', code: 87 },
  { name: 'An Giang', slug: 'an-giang', region: 'nam', code: 89 },
  { name: 'Kiên Giang', slug: 'kien-giang', region: 'nam', code: 91 },
  { name: 'Cần Thơ', slug: 'can-tho', region: 'nam', code: 92 },
  { name: 'Hậu Giang', slug: 'hau-giang', region: 'nam', code: 93 },
  { name: 'Sóc Trăng', slug: 'soc-trang', region: 'nam', code: 94 },
  { name: 'Bạc Liêu', slug: 'bac-lieu', region: 'nam', code: 95 },
  { name: 'Cà Mau', slug: 'ca-mau', region: 'nam', code: 96 },
]
