export const PROVINCES_SEED = [
  // 11 đơn vị không sắp xếp
  { name: 'Cao Bằng', slug: 'cao-bang', type: 'tinh' },
  { name: 'Điện Biên', slug: 'dien-bien', type: 'tinh' },
  { name: 'Hà Tĩnh', slug: 'ha-tinh', type: 'tinh' },
  { name: 'Lai Châu', slug: 'lai-chau', type: 'tinh' },
  { name: 'Lạng Sơn', slug: 'lang-son', type: 'tinh' },
  { name: 'Nghệ An', slug: 'nghe-an', type: 'tinh' },
  { name: 'Quảng Ninh', slug: 'quang-ninh', type: 'tinh' },
  { name: 'Thanh Hóa', slug: 'thanh-hoa', type: 'tinh' },
  { name: 'Sơn La', slug: 'son-la', type: 'tinh' },
  { name: 'Hà Nội', slug: 'ha-noi', type: 'thanh-pho' },
  { name: 'Huế', slug: 'hue', type: 'thanh-pho' },
  // 23 đơn vị hình thành sau sáp nhập
  { name: 'Tuyên Quang', slug: 'tuyen-quang', type: 'tinh' },
  { name: 'Lào Cai', slug: 'lao-cai', type: 'tinh' },
  { name: 'Thái Nguyên', slug: 'thai-nguyen', type: 'tinh' },
  { name: 'Phú Thọ', slug: 'phu-tho', type: 'tinh' },
  { name: 'Bắc Ninh', slug: 'bac-ninh', type: 'tinh' },
  { name: 'Hưng Yên', slug: 'hung-yen', type: 'tinh' },
  { name: 'Hải Phòng', slug: 'hai-phong', type: 'thanh-pho' },
  { name: 'Ninh Bình', slug: 'ninh-binh', type: 'tinh' },
  { name: 'Quảng Trị', slug: 'quang-tri', type: 'tinh' },
  { name: 'Đà Nẵng', slug: 'da-nang', type: 'thanh-pho' },
  { name: 'Quảng Ngãi', slug: 'quang-ngai', type: 'tinh' },
  { name: 'Gia Lai', slug: 'gia-lai', type: 'tinh' },
  { name: 'Khánh Hòa', slug: 'khanh-hoa', type: 'tinh' },
  { name: 'Lâm Đồng', slug: 'lam-dong', type: 'tinh' },
  { name: 'Đắk Lắk', slug: 'dak-lak', type: 'tinh' },
  { name: 'TP. Hồ Chí Minh', slug: 'tp-ho-chi-minh', type: 'thanh-pho' },
  { name: 'Đồng Nai', slug: 'dong-nai', type: 'tinh' },
  { name: 'Tây Ninh', slug: 'tay-ninh', type: 'tinh' },
  { name: 'Cần Thơ', slug: 'can-tho', type: 'thanh-pho' },
  { name: 'Vĩnh Long', slug: 'vinh-long', type: 'tinh' },
  { name: 'Đồng Tháp', slug: 'dong-thap', type: 'tinh' },
  { name: 'Cà Mau', slug: 'ca-mau', type: 'tinh' },
  { name: 'An Giang', slug: 'an-giang', type: 'tinh' },
] as const
