/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    subjects: Subject;
    provinces: Province;
    exams: Exam;
    posts: Post;
    events: Event;
    subscribers: Subscriber;
    notify_intents: NotifyIntent;
    interactions: Interaction;
    books: Book;
    affiliate_clicks: AffiliateClick;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subjects: SubjectsSelect<false> | SubjectsSelect<true>;
    provinces: ProvincesSelect<false> | ProvincesSelect<true>;
    exams: ExamsSelect<false> | ExamsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    notify_intents: NotifyIntentsSelect<false> | NotifyIntentsSelect<true>;
    interactions: InteractionsSelect<false> | InteractionsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    affiliate_clicks: AffiliateClicksSelect<false> | AffiliateClicksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    kho_de_sidebar_config: KhoDeSidebarConfig;
    'seo-config': SeoConfig;
    'search-config': SearchConfig;
  };
  globalsSelect: {
    kho_de_sidebar_config: KhoDeSidebarConfigSelect<false> | KhoDeSidebarConfigSelect<true>;
    'seo-config': SeoConfigSelect<false> | SeoConfigSelect<true>;
    'search-config': SearchConfigSelect<false> | SearchConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'editor' | 'reviewer' | 'student';
  avatar?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  purpose?: ('exam_content' | 'exam_answer' | 'exam_solution' | 'post_cover' | 'og_image' | 'other') | null;
  visibility?: ('public' | 'private') | null;
  checksum?: string | null;
  derivedMeta?: {
    pageCount?: number | null;
    width?: number | null;
    height?: number | null;
    avgColor?: string | null;
    firstPageThumbUrl?: string | null;
    webpVariants?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  watermarkedAt?: string | null;
  watermarkVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects".
 */
export interface Subject {
  id: string;
  name: string;
  slug: string;
  /**
   * Emoji hoặc URL
   */
  icon?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces".
 */
export interface Province {
  id: string;
  name: string;
  slug: string;
  type: 'tinh' | 'thanh-pho';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exams".
 */
export interface Exam {
  id: string;
  title: string;
  slug: string;
  category: 'vao-10' | 'vao-dai-hoc';
  examType: 'chinh-thuc' | 'thi-thu' | 'minh-hoa';
  year: '2020' | '2021' | '2022' | '2023' | '2024' | '2025' | '2026';
  /**
   * Ngày thi thật (hiển thị "Thi ngày ..." trên trang đề)
   */
  examDate?: string | null;
  /**
   * Số câu hỏi
   */
  totalQuestions?: number | null;
  /**
   * Thời lượng làm bài (phút)
   */
  durationMinutes?: number | null;
  /**
   * Tên trường THCS (autocomplete từ giá trị đã có)
   */
  school?: string | null;
  province?: (string | null) | Province;
  /**
   * Môn học (tuỳ chọn, dùng cho hub /mon-hoc/<slug>)
   */
  subject?: (string | null) | Subject;
  /**
   * Reviewer được giao kiểm duyệt (admin/editor pick)
   */
  assignedReviewer?: (string | null) | User;
  /**
   * Ghi chú cho reviewer (chỉ staff nội bộ: admin/editor/reviewer)
   */
  notesForReviewer?: string | null;
  /**
   * File đề PDF gốc (required khi publish)
   */
  pdfFile?: (string | null) | Media;
  /**
   * File đáp án (PDF hoặc image)
   */
  answerFile?: (string | null) | Media;
  /**
   * Cho phép làm bài online. Tick → hiện pill "Làm online" + nút "Làm bài" trên FE.
   */
  testOnline?: boolean | null;
  tags?: {
    hot?: {
      enabled?: boolean | null;
      /**
       * Auto-clear hot sau ngày này. Default: 7 ngày sau khi tick enabled.
       */
      expiresAt?: string | null;
    };
    hay?: boolean | null;
  };
  /**
   * Đề đã có file PDF. Tự động set từ pdfFile (read-only).
   */
  deReady?: boolean | null;
  /**
   * Đáp án đã có file. Tự động set từ answerFile (read-only).
   */
  dapAnReady?: boolean | null;
  /**
   * Lượt xem khởi điểm (seed). Sẽ cộng dồn lượt xem thật sau.
   */
  views?: number | null;
  /**
   * Cho phép tải PDF/đáp án về máy. Tắt → ẩn các nút Tải trên FE (đề thi + đáp án + mobile CTA).
   */
  allowDownload?: boolean | null;
  /**
   * Cho phép mở PDF trong tab mới (raw URL, KHÔNG có watermark FE). Tắt → ẩn nút "Mở tab mới" trên trang xem đề. Mặc định tắt vì lý do bảo vệ nội dung.
   */
  allowOpenInNewTab?: boolean | null;
  searchKey?: string | null;
  /**
   * SEO + Open Graph. Để trống = dùng fallback collection/global.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Tỉ lệ 1200×630 khuyến nghị. Để trống → web tự pick 1 trong 4 ảnh brand iStudy (random theo URL).
     */
    ogImage?: (string | null) | Media;
    ogTitle?: string | null;
    ogDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * Auto từ title nếu trống
   */
  slug?: string | null;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (string | null) | Media;
  author?: (string | null) | User;
  tags?: string[] | null;
  category: 'tu-vung' | 'ngu-phap' | 'meo' | 'tin-tuc';
  publishedAt?: string | null;
  isFeatured?: boolean | null;
  viewCount?: number | null;
  likeCount?: number | null;
  relatedPosts?: (string | Post)[] | null;
  relatedExams?: (string | Exam)[] | null;
  searchKeyPost?: string | null;
  /**
   * SEO + Open Graph. Để trống = dùng fallback collection/global.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Tỉ lệ 1200×630 khuyến nghị. Để trống → web tự pick 1 trong 4 ảnh brand iStudy (random theo URL).
     */
    ogImage?: (string | null) | Media;
    ogTitle?: string | null;
    ogDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  slug?: string | null;
  kind: 'live-exam' | 'announcement' | 'launch' | 'promo';
  startAt: string;
  endAt: string;
  cover?: (string | null) | Media;
  /**
   * [DEPRECATED] Surfaces array — giữ cho backward compat. Logic mới dùng submenu + BE algo (T1 3-state).
   */
  surfaces: ('header-mega' | 'homepage-hero' | 'cho-de')[];
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  registeredCount?: number | null;
  /**
   * Tên ngắn cho slot hẹp (mega-menu, chips). Default = title.
   */
  short?: string | null;
  /**
   * Caption in hoa phía trên title hero card (vd "Mùa thi 2026", "Tuyển sinh Hà Nội")
   */
  heroEyebrow?: string | null;
  /**
   * Giờ kỳ thi chính thức kết thúc (vd 09:30 sáng 27/06). Nhập tay. Required khi kind=live-exam.
   */
  examEndTime?: string | null;
  /**
   * Submenu mega-menu mặc định gắn với event
   */
  submenu:
    | 'vao-10'
    | 'thpt-qg'
    | 'dgnl'
    | 'quoc-te-de'
    | 'vao-10-thu'
    | 'thpt-qg-thu'
    | 'dgnl-thu'
    | 'quoc-te-thu'
    | 'thcs'
    | 'thpt'
    | 'quoc-te'
    | 'giao-tiep'
    | 'np-co-ban'
    | 'np-nang-cao'
    | 'tu-vung'
    | 'phat-am'
    | 'sgk'
    | 'bai-giang'
    | 'sach'
    | 'cong-cu';
  /**
   * Đề đã đăng. Khi true → state "de" (banner "Đề đã lên").
   */
  deReady?: boolean | null;
  /**
   * Đáp án đã có. Khi true → state "dap-an". Ưu tiên cao hơn deReady. Auto-tick deReady.
   */
  dapAnReady?: boolean | null;
  /**
   * Auto-set khi deReady chuyển 0→1
   */
  dePostedAt?: string | null;
  /**
   * Auto-set khi dapAnReady chuyển 0→1
   */
  dapAnPostedAt?: string | null;
  /**
   * Đề thi tương ứng — auto-derive examUrl/answerUrl
   */
  examRef?: (string | null) | Exam;
  /**
   * BE-internal: 1 = ưu tiên cao nhất. KHÔNG trả về FE.
   */
  priority?: number | null;
  /**
   * BE-internal: số ngày trước "date" mà event active. KHÔNG trả về FE.
   */
  leadDays?: number | null;
  /**
   * Multi-subject tương lai. Hiện cứng "Tiếng Anh".
   */
  subject?: string | null;
  /**
   * Force pin event vào slot cụ thể (override BE algo)
   */
  manualPin?: {
    hero?: boolean | null;
    popup?: boolean | null;
  };
  views?: number | null;
  searchKeyEvent?: string | null;
  /**
   * SEO + Open Graph. Để trống = dùng fallback collection/global.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Tỉ lệ 1200×630 khuyến nghị. Để trống → web tự pick 1 trong 4 ảnh brand iStudy (random theo URL).
     */
    ogImage?: (string | null) | Media;
    ogTitle?: string | null;
    ogDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: string;
  email: string;
  status: 'pending' | 'verified' | 'unsubscribed';
  verifyToken?: string | null;
  verifyTokenExpiresAt?: string | null;
  verifiedAt?: string | null;
  source?: ('newsletter' | 'notify-exam' | 'notify-event' | 'notify-feature' | 'notify-dap-an') | null;
  anonId?: string | null;
  resendContactId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notify_intents".
 */
export interface NotifyIntent {
  id: string;
  type: 'exam' | 'dap-an' | 'feature' | 'event';
  refSlug: string;
  email: string;
  anonId?: string | null;
  ua?: string | null;
  referer?: string | null;
  ip?: string | null;
  fulfilled?: boolean | null;
  fulfilledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interactions".
 */
export interface Interaction {
  id: string;
  anonId: string;
  refType: 'post' | 'exam';
  refId: string;
  kind: 'like' | 'bookmark';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: string;
  title: string;
  /**
   * Auto từ title nếu trống
   */
  slug?: string | null;
  author?: string | null;
  cover?: (string | null) | Media;
  shortDescription?: string | null;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL affiliate tới Shopee/Tiki/Fahasa
   */
  externalUrl: string;
  partner: 'shopee' | 'tiki' | 'fahasa' | 'self';
  price?: number | null;
  discountPrice?: number | null;
  category?: ('van-hoc' | 'giao-trinh' | 'tham-khao' | 'on-thi' | 'khac') | null;
  level?: ('tieu-hoc' | 'thcs' | 'thpt' | 'cao-dang-dai-hoc' | 'khac') | null;
  relatedExams?: (string | Exam)[] | null;
  relatedPosts?: (string | Post)[] | null;
  clickCount?: number | null;
  views?: number | null;
  /**
   * SEO + Open Graph. Để trống = dùng fallback collection/global.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Tỉ lệ 1200×630 khuyến nghị. Để trống → web tự pick 1 trong 4 ảnh brand iStudy (random theo URL).
     */
    ogImage?: (string | null) | Media;
    ogTitle?: string | null;
    ogDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Tracking 10% sample click affiliate sang Shopee/Tiki/Fahasa
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate_clicks".
 */
export interface AffiliateClick {
  id: string;
  book: string | Book;
  anonId?: string | null;
  clickedAt?: string | null;
  referer?: string | null;
  ua?: string | null;
  partner?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'subjects';
        value: string | Subject;
      } | null)
    | ({
        relationTo: 'provinces';
        value: string | Province;
      } | null)
    | ({
        relationTo: 'exams';
        value: string | Exam;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: string | Subscriber;
      } | null)
    | ({
        relationTo: 'notify_intents';
        value: string | NotifyIntent;
      } | null)
    | ({
        relationTo: 'interactions';
        value: string | Interaction;
      } | null)
    | ({
        relationTo: 'books';
        value: string | Book;
      } | null)
    | ({
        relationTo: 'affiliate_clicks';
        value: string | AffiliateClick;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  purpose?: T;
  visibility?: T;
  checksum?: T;
  derivedMeta?:
    | T
    | {
        pageCount?: T;
        width?: T;
        height?: T;
        avgColor?: T;
        firstPageThumbUrl?: T;
        webpVariants?: T;
      };
  watermarkedAt?: T;
  watermarkVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects_select".
 */
export interface SubjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces_select".
 */
export interface ProvincesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exams_select".
 */
export interface ExamsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  examType?: T;
  year?: T;
  examDate?: T;
  totalQuestions?: T;
  durationMinutes?: T;
  school?: T;
  province?: T;
  subject?: T;
  assignedReviewer?: T;
  notesForReviewer?: T;
  pdfFile?: T;
  answerFile?: T;
  testOnline?: T;
  tags?:
    | T
    | {
        hot?:
          | T
          | {
              enabled?: T;
              expiresAt?: T;
            };
        hay?: T;
      };
  deReady?: T;
  dapAnReady?: T;
  views?: T;
  allowDownload?: T;
  allowOpenInNewTab?: T;
  searchKey?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  cover?: T;
  author?: T;
  tags?: T;
  category?: T;
  publishedAt?: T;
  isFeatured?: T;
  viewCount?: T;
  likeCount?: T;
  relatedPosts?: T;
  relatedExams?: T;
  searchKeyPost?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  startAt?: T;
  endAt?: T;
  cover?: T;
  surfaces?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  body?: T;
  registeredCount?: T;
  short?: T;
  heroEyebrow?: T;
  examEndTime?: T;
  submenu?: T;
  deReady?: T;
  dapAnReady?: T;
  dePostedAt?: T;
  dapAnPostedAt?: T;
  examRef?: T;
  priority?: T;
  leadDays?: T;
  subject?: T;
  manualPin?:
    | T
    | {
        hero?: T;
        popup?: T;
      };
  views?: T;
  searchKeyEvent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  verifyToken?: T;
  verifyTokenExpiresAt?: T;
  verifiedAt?: T;
  source?: T;
  anonId?: T;
  resendContactId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notify_intents_select".
 */
export interface NotifyIntentsSelect<T extends boolean = true> {
  type?: T;
  refSlug?: T;
  email?: T;
  anonId?: T;
  ua?: T;
  referer?: T;
  ip?: T;
  fulfilled?: T;
  fulfilledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interactions_select".
 */
export interface InteractionsSelect<T extends boolean = true> {
  anonId?: T;
  refType?: T;
  refId?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  cover?: T;
  shortDescription?: T;
  fullDescription?: T;
  externalUrl?: T;
  partner?: T;
  price?: T;
  discountPrice?: T;
  category?: T;
  level?: T;
  relatedExams?: T;
  relatedPosts?: T;
  clickCount?: T;
  views?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        ogTitle?: T;
        ogDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate_clicks_select".
 */
export interface AffiliateClicksSelect<T extends boolean = true> {
  book?: T;
  anonId?: T;
  clickedAt?: T;
  referer?: T;
  ua?: T;
  partner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Cấu hình sidebar filter trang /kho-de-thi (groups + items)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kho_de_sidebar_config".
 */
export interface KhoDeSidebarConfig {
  id: string;
  groups?:
    | {
        title: string;
        items?:
          | {
              label: string;
              /**
               * Vd ?cat=vao-10&province=ha-noi
               */
              filterQuery: string;
              /**
               * Để trống = tự đếm từ DB. Có = override.
               */
              countOverride?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-config".
 */
export interface SeoConfig {
  id: string;
  siteName?: string | null;
  twitterHandle?: string | null;
  defaultTitle?: string | null;
  defaultTitleSuffix?: string | null;
  defaultDescription?: string | null;
  /**
   * Để trống → web dùng 4 ảnh brand mặc định (random theo URL). Set nếu muốn cố định 1 ảnh cho toàn site.
   */
  defaultOgImage?: (string | null) | Media;
  collectionDefaults?: {
    posts?: {
      ogImage?: (string | null) | Media;
    };
    exams?: {
      ogImage?: (string | null) | Media;
    };
    events?: {
      ogImage?: (string | null) | Media;
    };
    books?: {
      ogImage?: (string | null) | Media;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-config".
 */
export interface SearchConfig {
  id: string;
  popularTags?:
    | {
        id: string;
        label: string;
        hot?: boolean | null;
      }[]
    | null;
  provinces?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  trendingItems?:
    | {
        label: string;
        delta?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kho_de_sidebar_config_select".
 */
export interface KhoDeSidebarConfigSelect<T extends boolean = true> {
  groups?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              filterQuery?: T;
              countOverride?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-config_select".
 */
export interface SeoConfigSelect<T extends boolean = true> {
  siteName?: T;
  twitterHandle?: T;
  defaultTitle?: T;
  defaultTitleSuffix?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  collectionDefaults?:
    | T
    | {
        posts?:
          | T
          | {
              ogImage?: T;
            };
        exams?:
          | T
          | {
              ogImage?: T;
            };
        events?:
          | T
          | {
              ogImage?: T;
            };
        books?:
          | T
          | {
              ogImage?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-config_select".
 */
export interface SearchConfigSelect<T extends boolean = true> {
  popularTags?:
    | T
    | {
        id?: T;
        label?: T;
        hot?: T;
      };
  provinces?:
    | T
    | {
        name?: T;
        id?: T;
      };
  trendingItems?:
    | T
    | {
        label?: T;
        delta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'books';
          value: string | Book;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}